package de.gema.esb.service.partnerinteract.activitycontactmgmt.partnerinteraction_001_wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import de.gema.esb.service.partnerinteract.activitycontactmgmt.partnerinteractionabstract_001_wsdl.PartnerInteractionPortType;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-08-21T09:15:12.214+04:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "PartnerInteraction",
                  wsdlLocation = "file:/home/hakob/Documents/truckerDocs/Service/Sergey/boot-cxf-soap-demo-master/src/main/resources/ESB/Service/PartnerInteract/ActivityContactMgmt/PartnerInteraction/PartnerInteraction-001.wsdl",
                  targetNamespace = "http://www.gema.de/ESB/Service/PartnerInteract/ActivityContactMgmt/PartnerInteraction-001.wsdl")
public class PartnerInteraction extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.gema.de/ESB/Service/PartnerInteract/ActivityContactMgmt/PartnerInteraction-001.wsdl", "PartnerInteraction");
    public final static QName PartnerInteractionHttpEndpoint = new QName("http://www.gema.de/ESB/Service/PartnerInteract/ActivityContactMgmt/PartnerInteraction-001.wsdl", "PartnerInteractionHttpEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/hakob/Documents/truckerDocs/Service/Sergey/boot-cxf-soap-demo-master/src/main/resources/ESB/Service/PartnerInteract/ActivityContactMgmt/PartnerInteraction/PartnerInteraction-001.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PartnerInteraction.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/hakob/Documents/truckerDocs/Service/Sergey/boot-cxf-soap-demo-master/src/main/resources/ESB/Service/PartnerInteract/ActivityContactMgmt/PartnerInteraction/PartnerInteraction-001.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PartnerInteraction(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PartnerInteraction(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerInteraction() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PartnerInteraction(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PartnerInteraction(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PartnerInteraction(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PartnerInteractionPortType
     */
    @WebEndpoint(name = "PartnerInteractionHttpEndpoint")
    public PartnerInteractionPortType getPartnerInteractionHttpEndpoint() {
        return super.getPort(PartnerInteractionHttpEndpoint, PartnerInteractionPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartnerInteractionPortType
     */
    @WebEndpoint(name = "PartnerInteractionHttpEndpoint")
    public PartnerInteractionPortType getPartnerInteractionHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(PartnerInteractionHttpEndpoint, PartnerInteractionPortType.class, features);
    }

}
