
package de.gema.esb.service.base.baseabstract_001_wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-08-21T09:15:12.183+04:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "systemException", targetNamespace = "http://www.gema.de/ESB/Schema/Common/BaseTypes-001")
public class SystemESBException extends Exception {

    private de.gema.esb.schema.common.basetypes_001.SystemExceptionType systemException;

    public SystemESBException() {
        super();
    }

    public SystemESBException(String message) {
        super(message);
    }

    public SystemESBException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SystemESBException(String message, de.gema.esb.schema.common.basetypes_001.SystemExceptionType systemException) {
        super(message);
        this.systemException = systemException;
    }

    public SystemESBException(String message, de.gema.esb.schema.common.basetypes_001.SystemExceptionType systemException, java.lang.Throwable cause) {
        super(message, cause);
        this.systemException = systemException;
    }

    public de.gema.esb.schema.common.basetypes_001.SystemExceptionType getFaultInfo() {
        return this.systemException;
    }
}
