<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pi="PartnerService-001" xmlns:tns="PartnerServiceAbstract-001.wsdl"  name="PartnerService" targetNamespace="PartnerServiceAbstract-001.wsdl">
	<types>
		<xsd:schema>
			<xsd:import namespace="PartnerService-001" schemaLocation="../schema/Service-001.xsd"/>
		</xsd:schema>
	</types>
	<message name="createIncomingPostRequest">
		<part name="createIncomingPostRequest" element="pi:createIncomingPostRequest"/>
	</message>
	<message name="createIncomingPostResponse">
		<part name="createIncomingPostResponse" element="pi:createIncomingPostResponse"/>
	</message>
	<portType name="PartnerPortType">
		<operation name="createIncomingPost">
			<input name="createIncomingPostRequest" message="tns:createIncomingPostRequest"/>
			<output name="createIncomingPostResponse" message="tns:createIncomingPostResponse"/>
		</operation>
	</portType>
</definitions>
